### ISSUE TITLE
broken links in https://docs.solar.org/api/

### ISSUE THREAD

**Issue by crnazmija** [Solar-network/docs#4]
Links:
https://docs.solar.org/docs/api/public-rest-api/getting-started
https://docs.solar.org/docs/api/webhook-api/getting-started
https://docs.solar.org/docs/api/manager-api/getting-started

should be:

https://docs.solar.org/api/public-rest-api/getting-started
https://docs.solar.org/api/webhook-api/getting-started
https://docs.solar.org/api/manager-api/getting-started

**Comment by NayiemWillems** [comment]
Thank you for opening this issue.

The issue has been fixed in the following commit.
https://github.com/Solar-network/docs/commit/b6cbd425635b84971e2193ba0521cd713e3ce2a1
